server:
  port: 7709

feign:
  hystrix:
    enabled: true

spring:
  influx:
    url: http://172.16.100.68:8086
    user: admin
    password: admin
    report_msg_tags: temp,humi,lat,lng
    alarm_msg_tags: bindType,alarmType
    event_tags: event
  redis:
    host: redis
    port: 6379
    pool:
      max-active: 1024 #连接实例的最大数目
      max-wait: 10000  #控制一个pool最多有多少个状态为idle
      max-idle: 200    #等待可用连接的最大时间，单位毫秒
    timeout: 5000

retention_policy: default_policy

report:
  property:
    sn: sn
    lat: lat
    lng: lng

device_sum_sql: SELECT {0} FROM {1} where sn='{2}' and time>'{3}'and time <'{4}' tz('Asia/Shanghai')
group_sum_sql: SELECT {0} FROM {1} where groupId='{2}' and time>'{3}'and time <'{4}' tz('Asia/Shanghai')
